# your-repo-name/.github/workflows/first_workflow.yml

name: 'First Workflow'

on: push            

jobs:                         

  first-job:   

    name: 'Say hi'                           
    runs-on: 'ubuntu-latest'      
                         
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'develop'                         
    - name: 'Print a greeting'                             
      run:  mscoutermarsh/ascii-art-action@master 