name: 'Network rsk node workflow'
on: push      

jobs:                         
  get-posts-job:                            
    name: 'Print python message'                           

    runs-on: ubuntu-latest     
    steps:                             
      - name: 'Check-out the repo under $GITHUB_WORKSPACE'                               
        uses: actions/checkout@v2         
                                                                                                                
      - name: 'Test rsk node'                                 
        run: |
            curl -s -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_blockNumber", "params": {},  "id":123}' https://public-node.testnet.rsk.co | jq .result | tr -d '"' | awk '{print "printf \"%d\\n\" "$0}' | sh
